# Generated by Django 2.1 on 2019-12-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srv_title', models.CharField(max_length=150, verbose_name='Service Title')),
                ('srv_img', models.ImageField(blank=True, null=True, upload_to='img_uploads', verbose_name='Service Image')),
                ('srv_content', models.TextField(blank=True, verbose_name='Service Content')),
            ],
        ),
    ]
