# Generated by Django 2.1 on 2019-12-20 10:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_title', models.CharField(max_length=150, verbose_name='Website Name')),
                ('port_link', models.CharField(max_length=150, verbose_name='Web link')),
                ('port_img', models.ImageField(blank=True, null=True, upload_to='img_uploads', verbose_name='Post Image')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
        ),
    ]
