# Generated by Django 2.1 on 2019-12-20 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0002_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl_name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('cl_img', models.ImageField(blank=True, null=True, upload_to='img_uploads', verbose_name='Client Image')),
                ('cl_comment', models.TextField(blank=True, verbose_name='Client Commentt')),
            ],
        ),
    ]
