# Generated by Django 2.1 on 2020-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0004_suscribe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suscribe',
            name='email',
        ),
        migrations.AddField(
            model_name='suscribe',
            name='sc_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='port_link',
            field=models.URLField(max_length=150, verbose_name='Web link'),
        ),
    ]
