# Generated by Django 2.1 on 2020-01-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0005_auto_20200106_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sc_name', models.CharField(max_length=150, verbose_name='Client Name')),
                ('sc_email', models.EmailField(max_length=254, null=True, verbose_name='Client Name')),
            ],
        ),
        migrations.DeleteModel(
            name='Suscribe',
        ),
    ]
