# Generated by Django 2.1 on 2020-01-06 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0006_auto_20200106_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='sc_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Client Email'),
        ),
    ]
