# Generated by Django 2.1 on 2020-01-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0007_auto_20200106_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscribe',
            name='sc_name',
        ),
    ]
