# Generated by Django 2.1 on 2020-01-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0008_remove_subscribe_sc_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='sc_email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Email'),
        ),
    ]
