# Generated by Django 2.1 on 2020-01-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0009_auto_20200107_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='port_link',
            field=models.URLField(max_length=150, null=True, verbose_name='Web link'),
        ),
        migrations.AlterField(
            model_name='subscribe',
            name='sc_email',
            field=models.EmailField(max_length=254, null=True, verbose_name=''),
        ),
    ]
