# Generated by Django 2.1 on 2020-01-14 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0010_auto_20200114_0907'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mycv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mycv_file', models.FileField(null=True, upload_to='', verbose_name='My Cv')),
            ],
        ),
    ]
