# Generated by Django 2.1 on 2020-01-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0012_auto_20200114_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mycv',
            name='mycv_file',
            field=models.FileField(null=True, upload_to='', verbose_name='mycv'),
        ),
    ]
