# Generated by Django 2.1 on 2020-01-14 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seyi_web_app', '0013_auto_20200114_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='mycv',
            name='name',
            field=models.CharField(default='', max_length=40),
        ),
    ]
